// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
)

type Querier interface {
	// user/query.sql
	// ------------------------------------------------------------
	// Users basic queries for sqlc (SQLite engine)
	// Schema: id INTEGER PK, email TEXT UNIQUE, password_hash TEXT, created_at DATETIME
	// ------------------------------------------------------------
	// Create a new user and return the generated row --------------------------------
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	// Delete a user -----------------------------------------------------------------
	DeleteUser(ctx context.Context, id int64) error
	// Fetch a user by unique email ---------------------------------------------------
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// Fetch a user by primary key ----------------------------------------------------
	GetUserByID(ctx context.Context, id int64) (User, error)
	// List active users (simple pagination) -----------------------------------------
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	// Update only the password hash --------------------------------------------------
	UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error
}

var _ Querier = (*Queries)(nil)
